version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "8080:80"
    depends_on:
      - api
      - db
    networks:
      - nostromo_net

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      - DB_HOST=db
      - PASSWORD_API=claveSuperSecreta123
    networks:
      - nostromo_net

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bd_nostromo
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - nostromo_net

  adminer:
    image: adminer
    ports:
      - "8082:8080"
    networks:
      - nostromo_net

networks:
  nostromo_net:
