services:
  - type: web
    name: nostromo-web
    env: docker
    plan: free
    dockerfilePath: Dockerfile.app
    autoDeploy: true
    envVars:
      - key: DB_HOST
        value: nostromo-db
      - key: PASSWORD_API
        value: claveSuperSecreta123

  - type: web
    name: nostromo-api
    env: docker
    plan: free
    dockerfilePath: Dockerfile.api
    autoDeploy: true
    envVars:
      - key: DB_HOST
        value: nostromo-db
      - key: PASSWORD_API
        value: claveSuperSecreta123

  - type: pserv
    name: nostromo-db
    env: docker
    plan: free
    image:
      url: "mysql:8.0"
    autoDeploy: false
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: root
      - key: MYSQL_DATABASE
        value: bd_nostromo

  - type: pserv
    name: nostromo-adminer
    env: docker
    plan: free
    image:
      url: "adminer"
    autoDeploy: false
