services:
  - type: web
    name: nostromo-web
    env: docker
    plan: free
    dockerfilePath: Dockerfile.app
    buildCommand: ""
    startCommand: ""
    autoDeploy: true
    ports:
      - 80
    envVars:
      - key: DB_HOST
        value: nostromo-db
      - key: PASSWORD_API
        value: claveSuperSecreta123

  - type: web
    name: nostromo-api
    env: docker
    plan: free
    dockerfilePath: Dockerfile.api
    buildCommand: ""
    startCommand: ""
    autoDeploy: true
    ports:
      - 80
    envVars:
      - key: DB_HOST
        value: nostromo-db
      - key: PASSWORD_API
        value: claveSuperSecreta123

  - type: web
    name: nostromo-adminer
    env: docker
    plan: free
    dockerfilePath: ""
    image: adminer
    startCommand: ""
    autoDeploy: false
    ports:
      - 8082

  - type: web
    name: nostromo-db
    env: docker
    plan: free
    dockerfilePath: ""
    image: mysql:8.0
    startCommand: ""
    autoDeploy: false
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: root
      - key: MYSQL_DATABASE
        value: bd_nostromo
