FROM php:8.2-apache

COPY ./servicios_rest/ /var/www/html/

COPY apache.conf /etc/apache2/conf-available/override.conf

RUN docker-php-ext-install mysqli \
    && a2enmod rewrite \
    && a2enconf override

EXPOSE 10000
